# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'From.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(693, 458)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 390, 171, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 361, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 160, 367, 52))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.doubleSpinBox.setMaximum(1000.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.doubleSpinBox_2.setMaximum(1000.0)
        self.doubleSpinBox_2.setSingleStep(0.1)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 70, 363, 83))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.doubleSpinBox_minw = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_minw.setMaximum(9999.0)
        self.doubleSpinBox_minw.setSingleStep(0.1)
        self.doubleSpinBox_minw.setObjectName("doubleSpinBox_minw")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_minw)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.doubleSpinBox_maxw = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_maxw.setMaximum(9999.0)
        self.doubleSpinBox_maxw.setSingleStep(0.1)
        self.doubleSpinBox_maxw.setObjectName("doubleSpinBox_maxw")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_maxw)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.doubleSpinBox_mixh = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_mixh.setMaximum(9999.0)
        self.doubleSpinBox_mixh.setSingleStep(0.1)
        self.doubleSpinBox_mixh.setObjectName("doubleSpinBox_mixh")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_mixh)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.doubleSpinBox_maxh = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_maxh.setMaximum(9999.0)
        self.doubleSpinBox_maxh.setSingleStep(0.1)
        self.doubleSpinBox_maxh.setObjectName("doubleSpinBox_maxh")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_maxh)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_6.addWidget(self.label_15)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(10, 230, 171, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 260, 361, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(70, 320, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 320, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(80, 360, 72, 15))
        self.label_18.setObjectName("label_18")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(240, 350, 72, 15))
        self.label_16.setObjectName("label_16")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(390, 20, 291, 421))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "word图片批量修改器 V 1.0"))
        self.pushButton_2.setText(_translate("Form", "开始转换"))
        self.label.setText(_translate("Form", "请选择文件"))
        self.pushButton.setText(_translate("Form", "选择文件"))
        self.label_6.setText(_translate("Form", "图片尺寸设置"))
        self.label_2.setText(_translate("Form", "图片宽度"))
        self.label_3.setText(_translate("Form", "mm"))
        self.label_4.setText(_translate("Form", "图片高度"))
        self.label_5.setText(_translate("Form", "mm"))
        self.label_7.setText(_translate("Form", "参与调整的图片尺寸限制"))
        self.label_8.setText(_translate("Form", "最小宽度"))
        self.label_12.setText(_translate("Form", "mm"))
        self.label_9.setText(_translate("Form", "最大宽度"))
        self.label_14.setText(_translate("Form", "mm"))
        self.label_10.setText(_translate("Form", "最小高度"))
        self.label_13.setText(_translate("Form", "mm"))
        self.label_11.setText(_translate("Form", "最大高度"))
        self.label_15.setText(_translate("Form", "mm"))
        self.label_17.setText(_translate("Form", "请输入要修改的章节名称"))
        self.pushButton_3.setText(_translate("Form", "保存配置"))
        self.pushButton_4.setText(_translate("Form", "读取上次配置"))
        self.label_18.setText(_translate("Form", "等待保存"))
        self.label_16.setText(_translate("Form", "等待读取"))


